author: ${project.authors}
main: ${project.main}
version: ${project.version}
name: ${project.name}
softdepend: ${project.softdepends}
commands:
  biab:
    usage: "/<command> [list [<page>]|[give [<player>]|save|delete|reload] <buildingname>]"
    description: give a player a Build-in-a-Box Building.

permissions:
  biab.select:
    default: op
  biab.save:
    default: op
  biab.permanent:
    default: op
  biab.delete:
    default: op
  biab.unlock.others:
    description: allow unlocking BIAB's locked by other players.
    default: true